<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MinGo.Application\MinGo.Application.csproj" />
    <ProjectReference Include="..\MinGo.Infrastructure\MinGo.Infrastructure.csproj" />
    <ProjectReference Include="..\MinGo.Core\MinGo.Core.csproj" />
    <ProjectReference Include="..\MinGo.Shared\MinGo.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Vite.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />

  </ItemGroup>

  <ItemGroup>
    <Folder Include="Kestrel\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles> -->
    <!-- <CompilerGeneratedFilesOutputPath>.</CompilerGeneratedFilesOutputPath> -->
    <UserSecretsId>a64d4464-4200-4f10-8cc6-5f5d06b4931e</UserSecretsId>
  </PropertyGroup>

</Project>