// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinGo.ControlPlane.Data;

#nullable disable

namespace MinGo.ControlPlane.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260304085908_GatewayInstances")]
    partial class GatewayInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MinGo.ControlPlane.Data.ClusterConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthCheckJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadBalancingPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GatewayConfigId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.DestinationConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Healthy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterConfigId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.GatewayConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonitoringJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GatewayConfigs");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.GatewayInstanceEntity", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<long>("ErrorRequests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstanceId");

                    b.HasIndex("LastHeartbeat");

                    b.HasIndex("Status");

                    b.ToTable("GatewayInstances");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.RouteConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewayConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GatewayConfigId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.ClusterConfigEntity", b =>
                {
                    b.HasOne("MinGo.ControlPlane.Data.GatewayConfigEntity", "GatewayConfig")
                        .WithMany("Clusters")
                        .HasForeignKey("GatewayConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GatewayConfig");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.DestinationConfigEntity", b =>
                {
                    b.HasOne("MinGo.ControlPlane.Data.ClusterConfigEntity", "ClusterConfig")
                        .WithMany("Destinations")
                        .HasForeignKey("ClusterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClusterConfig");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.RouteConfigEntity", b =>
                {
                    b.HasOne("MinGo.ControlPlane.Data.GatewayConfigEntity", "GatewayConfig")
                        .WithMany("Routes")
                        .HasForeignKey("GatewayConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GatewayConfig");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.ClusterConfigEntity", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("MinGo.ControlPlane.Data.GatewayConfigEntity", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
